# Generated by Django 4.1.1 on 2022-12-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_cpu_model_customuser_gpu_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpu_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cpu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gpu_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gpu'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ram_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ram'),
        ),
    ]
